### ISSUE TITLE
Tutorial files will not run

### ISSUE THREAD

**Issue by HenryWede** [martinmcbride/generativepy#4]
Hello,

I am trying to run the very first tutorial file:
generativepy / tutorial/ getting-started / rectangle.py

which seems like the same code located at:
https://www.pythoninformer.com/generative-art/generativepy-tutorial/simple-image/

and it creates the following error message:

python GenerativeExample1.py
Traceback (most recent call last):
  File "C:\Users\henry\Documents\Python\GenerativeExample1.py", line 3, in <module>
    from generativepy.geometry import Rectangle
  File "C:\Program Files\Python39\lib\site-packages\generativepy\geometry.py", line 7, in <module>
    from easy_vector import Vector
ModuleNotFoundError: No module named 'easy_vector'

for reference, here is the folder in site-packages:
 Directory of C:\Program Files\Python39\Lib\site-packages\generativepy

06/19/2022  03:02 PM    <DIR>          .
06/19/2022  03:02 PM    <DIR>          ..
06/19/2022  03:02 PM               813 analytics.py
06/19/2022  03:02 PM             4,314 bitmap.py
06/19/2022  03:02 PM            15,277 color.py
06/19/2022  03:02 PM             5,184 drawing.py
06/19/2022  03:02 PM             3,072 drawing3d.py
06/19/2022  03:02 PM             4,037 formulas.py
06/19/2022  03:02 PM            38,721 geometry.py
06/19/2022  03:02 PM             3,673 geometry3d.py
06/19/2022  03:02 PM               746 gif.py
06/19/2022  03:02 PM            16,761 graph.py
06/19/2022  03:02 PM             5,650 movie.py
06/19/2022  03:02 PM             5,844 nparray.py
06/19/2022  03:02 PM             7,231 tween.py
06/19/2022  03:02 PM             1,134 utils.py
06/19/2022  03:02 PM                22 __init__.py
06/19/2022  03:02 PM    <DIR>          __pycache__
              15 File(s)        112,479 bytes
               3 Dir(s)  349,695,762,432 bytes free

Thanks for your help

**Comment by 1rach** [comment]
Install easy_vector, try :  
`pip install easy_vector`
or 
`pip3 install easy_vector`

**Comment by martinmcbride** [comment]
New version 50.00 will consolidate all examples on graphicmaths.com, see readme.md
